jobs:
- job: myJob
  timeoutInMinutes: 10
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - bash: az --version
  displayName: 'Show Azure CLI version'
  -bash: az pipelines build list
  displayName: 'Show build list and PRs'